export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=sway
path+=/opt/Bitwarden
export PATH
export PROMPT="%F{blue}%~%f  "

# autostart sway
if [[ "$(tty)" == "/dev/tty1" ]]
    then
        exec dbus-run-session sway
fi

# add tere
tere() {
    local result=$(command tere "$@")
    [ -n "$result" ] && cd -- "$result"
}

# completion stuff
zstyle :compinstall filename '/home/tim/.zshrc'
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s

autoload -Uz compinit
compinit

# fix keys >:(
bindkey "^[[3~" delete-char

HISTFILE=~/.histfile
HISTSIZE=500
SAVEHIST=10

# plugins
source ~/.zsh/plugins/fsh/fast-syntax-highlighting.plugin.zsh

alias vi=nvim
alias vim=nvim
alias clag=clang
alias sudo=doas
alias open=thunar
